### ISSUE TITLE
Implement "Firebase-Hosting" to Application

### ISSUE THREAD

**Issue by SoftEngAliijaz** [SoftEngAliijaz/shopbiz_app#10]
### Host the application using Firebase Hosting, following best practices and security guidelines.

**Tasks:**

- [x] Set up Firebase Hosting
- [x] Configure DNS settings
- [x] Deploy application to Firebase Hosting
- [x] Implement SSL encryption
- [x] Configure custom domain (optional)
- [x] Test deployment for security and functionality

Resources

Refer to one of the following tutorials:

- [x] [Video 1](https://youtu.be/ZeUN3l6k5UY?si=wGS2B8LHGgcd7mSr)
- [x] [Video 2](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://www.youtube.com/watch%3Fv%3Dv8mFIm-FNyA&ved=2ahUKEwirwM7F4pOJAxVp2AIHHbMKOqUQwqsBegQIExAG&usg=AOvVaw3P3foJvxNETnFG1YuD3hWt)
